onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - aws-sdk
  - prisma
  - sharp
  - unrs-resolver

overrides:
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  hono@<4.10.3: '>=4.10.3'
  hono@<4.9.7: '>=4.9.7'
  hono@>=1.1.0 <4.10.2: '>=4.10.2'
